version: '3.8'

services:
  # 1. SERVER
  vsc_backend:
    volumes:
      - ${SSL_KEY_PATH:-/dev/null}:${SSL_KEY_PATH:-/dev/null}:ro
      - ${SSL_CERT_PATH:-/dev/null}:${SSL_CERT_PATH:-/dev/null}:ro
      - ${SSL_INTERMEDIATE_PATH:-/dev/null}:${SSL_INTERMEDIATE_PATH:-/dev/null}:ro
    build: .
    container_name: vsc_chat_backend
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    environment:
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_INTERMEDIATE_PATH=${SSL_INTERMEDIATE_PATH}
      - HTTP_PORT=${HTTP_PORT}
      - SOCKET_PORT=${SOCKET_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PUBLIC_STORAGE_HOST=${PUBLIC_STORAGE_HOST}
      - PUBLIC_STORAGE_PORT=${PUBLIC_STORAGE_PORT}
      - PUBLIC_STORAGE_SSL=${PUBLIC_STORAGE_SSL}
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - STORAGE_PORT=${MINIO_PORT}
      - STORAGE_ACCESS_KEY=${MINIO_ADMIN_USER}
      - STORAGE_SECRET_KEY=${MINIO_ADMIN_PASSWORD}
    depends_on:
      vsc_datenbank:
        condition: service_healthy # 👈 Wartet, bis der Healthcheck der DB "green" ist
      vsc-storage:
        condition: service_started

  # 2. DEINE DATENBANK
  vsc_datenbank:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      timeout: 5s
      retries: 5
      interval: 5s
    container_name: vschat_db
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_local_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    # HIER IST DIE MAGIE:
    networks:
      default:
        aliases:
          - ${DB_HOST}


  vsc-storage:
    image: minio/minio:latest
    container_name: vsc_chat_minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ADMIN_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ADMIN_PASSWORD}
      MINIO_API_CORS_ALLOW_ORIGIN: '*'
    volumes: 
      - minio_local_data:/data
    command: server /data --console-address :${MINIO_CONSOLE_PORT}
    networks:
      default:
        aliases:
          - ${STORAGE_ENDPOINT}

volumes:
  mysql_local_data:
  minio_local_data:
